name: Release

on:
  push:
    branches: [main]
    paths: [pyproject.toml]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: greener-hayden/workflows/.github/workflows/release.yml@v1
    with:
      kind: pyinstaller
      name: nvidiot
      version_file: pyproject.toml
      version_pattern: '^version = "\(.*\)"'
